#!/usr/bin/env python3
"""Reconcile papers/pdf/ against the vault and papers/wanted.yml.

Answers three questions and regenerates papers/WANTED.md from the answers, so
the wishlist cannot drift out of date:

  1. Which vault notes cite an eprint whose PDF is not in papers/pdf/?
  2. Which curated wishlist entries are still missing?
  3. Which PDFs are present but not cited by any vault note?

    python3 scripts/check_pdfs.py           # report
    python3 scripts/check_pdfs.py --write   # regenerate papers/WANTED.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from kb import REPO_ROOT, collect_notes, load_schema

PDF_DIR = REPO_ROOT / "papers" / "pdf"
WANTED_YML = REPO_ROOT / "papers" / "wanted.yml"
WANTED_MD = REPO_ROOT / "papers" / "WANTED.md"


def pdf_name(eprint: str) -> str:
    return eprint.replace("/", "-") + ".pdf"


def local_pdf(eprint: str) -> Path | None:
    candidate = PDF_DIR / pdf_name(eprint)
    return candidate if candidate.exists() else None


def load_wanted() -> list[dict]:
    if not WANTED_YML.exists():
        return []
    data = yaml.safe_load(WANTED_YML.read_text(encoding="utf-8")) or {}
    return data.get("wanted", []) or []


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate papers/WANTED.md")
    args = parser.parse_args()

    schema = load_schema()
    notes, issues = collect_notes(schema)
    if issues:
        print(f"warning: vault has {len(issues)} schema error(s); "
              "run scripts/validate.py", file=sys.stderr)

    cited: dict[str, list] = {}
    for note in notes.values():
        eprint = note.fields.get("eprint")
        if eprint:
            cited.setdefault(str(eprint), []).append(note)

    have = {p.name for p in PDF_DIR.glob("*.pdf")} if PDF_DIR.is_dir() else set()

    missing_cited = sorted(
        (ep, cited[ep]) for ep in cited if pdf_name(ep) not in have
    )
    present_cited = sorted(ep for ep in cited if pdf_name(ep) in have)

    wanted = load_wanted()
    still_wanted = [
        entry
        for entry in wanted
        if not entry.get("eprint") or pdf_name(str(entry["eprint"])) not in have
    ]
    now_satisfied = [
        entry
        for entry in wanted
        if entry.get("eprint") and pdf_name(str(entry["eprint"])) in have
    ]

    cited_files = {pdf_name(ep) for ep in cited}
    uncited_pdfs = sorted(f for f in have if f not in cited_files)

    print(f"papers/pdf/: {len(have)} PDF(s)")
    print(f"  cited by a vault note and present:  {len(present_cited)}")
    print(f"  cited by a vault note but missing:  {len(missing_cited)}")
    print(f"  curated wishlist still missing:     {len(still_wanted)}")
    print(f"  present but not cited by any note:  {len(uncited_pdfs)}")

    if missing_cited:
        print("\nmissing PDFs for papers already in the vault:")
        for eprint, note_list in missing_cited:
            ids = ", ".join(sorted(n.id for n in note_list))
            print(f"  {eprint:<12} {pdf_name(eprint):<18} ({ids})")

    if now_satisfied:
        print("\nwishlist entries satisfied (remove from papers/wanted.yml):")
        for entry in now_satisfied:
            print(f"  {entry['eprint']}  {entry.get('title', '')[:60]}")

    if uncited_pdfs:
        print("\nPDFs with no citing vault note:")
        for name in uncited_pdfs:
            print(f"  {name}")

    if args.write:
        WANTED_MD.write_text(render(missing_cited, still_wanted, uncited_pdfs, have),
                             encoding="utf-8")
        print(f"\nwrote {WANTED_MD.relative_to(REPO_ROOT)}")

    return 0


def render(missing_cited, still_wanted, uncited_pdfs, have) -> str:
    out = [
        "# Wanted papers",
        "",
        "Generated by `scripts/check_pdfs.py --write`. Do not edit by hand: add or",
        "remove entries in `papers/wanted.yml` and regenerate. Anything whose PDF",
        "lands in `papers/pdf/` drops off this list automatically.",
        "",
        f"`papers/pdf/` currently holds **{len(have)}** PDFs.",
        "",
        "Save each file as its eprint id with the slash replaced by a hyphen, for",
        "example `2024-669.pdf`. Prefer the eprint version over a publisher PDF:",
        "eprint submissions are CC BY or author-retained, publisher PDFs are not.",
        "",
    ]

    out += ["## Cited by a vault note, PDF missing", ""]
    if missing_cited:
        out += [
            "These are the sharpest gaps: a note already makes claims about the paper.",
            "",
            "| eprint | save as | cited by | link |",
            "|---|---|---|---|",
        ]
        for eprint, notes in missing_cited:
            ids = ", ".join(f"`{n.id}`" for n in sorted(notes, key=lambda n: n.id))
            out.append(
                f"| `{eprint}` | `{pdf_name(eprint)}` | {ids} | "
                f"[pdf](https://eprint.iacr.org/{eprint}.pdf) |"
            )
        out.append("")
    else:
        out += ["None. Every paper cited by a vault note has its PDF.", ""]

    by_priority: dict[int, list[dict]] = {}
    for entry in still_wanted:
        by_priority.setdefault(int(entry.get("priority", 3)), []).append(entry)

    labels = {
        1: "Priority 1: the KB makes a claim it cannot fully source",
        2: "Priority 2: would let an existing note go deeper",
        3: "Priority 3: provenance and completeness",
    }

    out += ["## Curated wishlist", ""]
    if not still_wanted:
        out += ["Empty. Everything in `papers/wanted.yml` has arrived.", ""]
    for priority in sorted(by_priority):
        out += [f"### {labels.get(priority, priority)}", ""]
        for entry in by_priority[priority]:
            eprint = entry.get("eprint")
            title = entry.get("title", "(untitled)")
            authors = entry.get("authors")
            venue = entry.get("venue")
            url = entry.get("url")
            head = f"**{title}**"
            if authors:
                head += f" - {authors}"
            if venue:
                head += f" ({venue})"
            out.append(f"- {head}")
            if eprint:
                out.append(
                    f"  - `{eprint}` -> save as `{pdf_name(str(eprint))}` - "
                    f"[pdf](https://eprint.iacr.org/{eprint}.pdf)"
                )
            elif url:
                out.append(f"  - [{url}]({url})")
            else:
                out.append("  - no verified identifier yet; do not cite one until confirmed")
            why = " ".join(str(entry.get("why", "")).split())
            if why:
                out.append(f"  - {why}")
        out.append("")

    if uncited_pdfs:
        out += [
            "## Present but not cited by any vault note",
            "",
            "Either the note is still to be written, or the file is misnamed.",
            "",
        ]
        out += [f"- `{name}`" for name in uncited_pdfs]
        out.append("")

    return "\n".join(out)


if __name__ == "__main__":
    sys.exit(main())
